### ISSUE TITLE
Error encrypting value: object type

### ISSUE THREAD

**Issue by benpturner** [nettitude/PoshC2_Python#1]
If you get this error after installing PoshC2 try creating a virtualenv in python and re-install the requirements. Make sure you deactivate when you've finished in this virtualenv. 

pip install virtualenv
virtualenv /opt/PoshC2_Python/
source /opt/PoshC2_Python/bin/activate
pip install -r requirements.txt

**Comment by m0rv4i** [comment]
Added to README
