### ISSUE TITLE
Can't seem to figure out sharpsocks

### ISSUE THREAD

**Issue by jmhickman** [nettitude/PoshC2_Python#11]
With a otherwise normally running implant, I can't seem to understand what I'm supposed to do in order to use the sharpsocks proxy.

The docs say that a command of the form 
`SharpSocks -Uri https://www.c2.com:443 -Beacon 2000 -Insecure`   
is supposed to get me up and running. 

However, substituting my C2 server for the -uri (which is what I think I'm supposed to put there, the doc is unclear), I get
```
[-] Loading Assemblies
```
And then nothing.

If I just write 'sharpsocks' however, a seemingly fully automatic routine kicks in, which assembles the following invocation. (I'm fine with the key leak, this is just a temp testing instance):
```
Sharpsocks -Client -Uri https://192.168.10.3 -Channel mgjMOcupaHiHIyATayeYHSTsN -Key RRC1DX0CZqqh4PCEHD4yC/fMRW9VX+AW/iEl8S1qKMI= -URLs api/v1/socks5/,api/v1/socks/ -Insecure -Beacon 2000
```
Which results in:
```
[-] Loading Assemblies

[+] SharpSocks client Started!

URLs:
https://192.168.10.3/api/v1/socks5/
https://192.168.10.3/api/v1/socks/
Channel: mgjMOcupaHiHIyATayeYHSTsN
Key being used: RRC1DX0CZqqh4PCEHD4yC/fMRW9VX+AW/iEl8S1qKMI=
Beacon: 20
Cookies: ASP.NET_SessionId __RequestVerificationToken
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36


[-] Run StopSocks to stop the client!
```

That seems like it is working, but the issue is that I can't seem to find what port on the C2server's host I'm supposed to direct traffic through to take advantage of the proxy. Issuing `ss -npl` on my C2 host doesn't show any new listening ports.

Any input on what I'm missing/doing wrong would be a big help.

**Comment by benpturner** [comment]
So you need to run the server side too, unfortunately this doesn't integrate into PoshC2 as you might think, its a standalone module. This can be run under wine but only appears to work over HTTP. When deploying we usually have a C2 Proxy that takes it from HTTPS on the proxy and downgrades to HTTP. It should be noted its all encrypted even over HTTP anyway. 

The server side should be run too like this

SharpSocksServerTestApp.exe -c raFAdgVuuRFYgKHqp -k fFaKiMspoTWHvpzTkuq+VKDp+h1X79q3gXQ= -l https://10.0.0.1:8888 -s 43334

When the server connects it should tell you and open port 43334 so you can then point proxychains at this. I'm available on the slack channel if you want to have a discussion about this.

**Comment by jmhickman** [comment]
Ah, I see. So that .txt file in the repo is referring to instructions on how to get the standalone component up and running. I didn't know if it was current or not since the docs don't refer to it.

I'll mess around with it some more and see how it goes. Thank you for the quick reply!

**Comment by m0rv4i** [comment]
Sounds like things are resolved :), any further issues please open on the SharpSocks repo:
https://github.com/nettitude/SharpSocks
