### ISSUE TITLE
Watson / Sherlock

### ISSUE THREAD

**Issue by BaffledJimmy** [nettitude/PoshC2_Python#19]
Hey Ben,

Would it be OK to get Rasta's CSharp implementation of Sherlock (which is now deprecated) into Posh pls? I see lots of other CSharp assemblies are making their way in too :)

https://github.com/rasta-mouse/Watson

Thanks!

**Comment by benpturner** [comment]
Fancy doing a PR :D

**Comment by m0rv4i** [comment]
In on the dev branch, will get merged in next release.
