### ISSUE TITLE
Strange console/printline behavior in C2Viewer.py

### ISSUE THREAD

**Issue by jmhickman** [nettitude/PoshC2_Python#32]
Running clean install of 4.7 (issue also appears in 4.6), no update script used. Only `Config.py` changes were IP address and port configuration for my setup.
```
root@posh # python --version  
Python 2.7.15rc1
```
`C2Viewer.py`, when run, will continuously print an empty newline to the console when the following conditions are met:
 * No 'command returned against implant' messages have occurred since the `C2Viewer.py` script was started.  
 * A new c# implant checks in (tested with Sharp_x64.dll).

There is no anomalous output in the journal view of `C2Server.py`. 

`C2Viewer.py` also prints an integer to the console when it starts, that seems to be related to the cumulative number of commands entered into `ImplantHandler.py`.

**Comment by benpturner** [comment]
Can't seem to repo this, the C2Viewer seems to work ok, I did remove the print statement for the taskid not sure if that was the issue or not. It was in there for testing, the C2Viewer was only created for a backup to be honest, the journalctl is the better way to run it or in a screen session but completely up to you

**Comment by jmhickman** [comment]
If it's mostly deprecated then I'm fine ignoring the issue.
