### ISSUE TITLE
File downloads 

### ISSUE THREAD

**Issue by lhagan-eth** [nettitude/PoshC2_Python#34]
When downloading files from implants, no checks are done to confirm if a file with the same name has previously been downloaded. This means the original file which was downloaded gets appended with the data from the new download.

**Comment by m0rv4i** [comment]
Fix pushed on https://github.com/nettitude/PoshC2_Python/tree/file-download branch, if you can test I'll merge it!

**Comment by m0rv4i** [comment]
This has been fixed in 4.8
