### ISSUE TITLE
Error in starting c2server.py in POSHC2(python)

### ISSUE THREAD

**Issue by praveenp13** [nettitude/PoshC2_Python#40]
Hi,

I am getting the below error while starting C2Server.py (python). I tried on on Kali with Python 2.7.15 running..

Error:-

Initializing new project folder and database

Traceback (most recent call last):
  File "C2Server.py", line 423, in <module>
    initializedb()
  File "/opt/PoshC2_Python/DB.py", line 96, in initializedb
    conn = sqlite3.connect(Database)
sqlite3.OperationalError: unable to open database file

**Comment by benpturner** [comment]
When this happens, you need to remove the project folder, typically the /opt/PoshC2_Project/ as there may have been an issue starting and now doesnt have a sqlite file

**Comment by m0rv4i** [comment]
Closing dead issue.
