### ISSUE TITLE
Sessions all down suddenly

### ISSUE THREAD

**Issue by kumara19bara** [nettitude/PoshC2_Python#45]
I got this error after 20 min after activating a session, and then it goes down:
`'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "C2Server.py", line 325, in do_POST
    cookieVal = (s.cookieHeader).replace("SessionID=", "")
AttributeError: 'NoneType' object has no attribute 'replace'

'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "C2Server.py", line 325, in do_POST
    cookieVal = (s.cookieHeader).replace("SessionID=", "")
AttributeError: 'NoneType' object has no attribute 'replace'`

**Comment by benpturner** [comment]
Hi, 

Sorry to hear about this, can you provide a little more information on this. Does this happen every time after 20 minutes or did you run a certain command to trigger this error. If so can you let us know what those commands were. 

Thanks

**Comment by benpturner** [comment]
Also, was the implant fully working in the 20 minutes you had it up? E.g. could you run commands and see the output?

**Comment by kumara19bara** [comment]
Actually it was may launch break, i left the sessions active (idle without any task) and when I came back I found the error.
I've got new sessions but I wanted to share the issue to perfect this nice tool.
( I trying to fix the issue with an initialisation of the variable s(.cookieHeader) and a try catch. but I think that maybe it can be fixed with a more reliable way.

Thanks

**Comment by m0rv4i** [comment]
Thanks for your kind words :) 

This is a strange one, @benpturner there should always be a cookie right for a post request?

@kumara19bara can you confirm you're using the most recent version and you're using the `posh` and `posh-server` commands to run the tool or equivalent?

**Comment by kumara19bara** [comment]
yes I just installed the latest version because of the issue. and got the same error again. I think that some of request may be stopped by the AV.

**Comment by m0rv4i** [comment]
Are you still encountering this issue?

**Comment by kumara19bara** [comment]
it is working perfectly after the last update, thank you.
Keep the hard work in this awesome project.
cheerzz
