### ISSUE TITLE
Output Truncated

### ISSUE THREAD

**Issue by chppppp** [nettitude/PoshC2_Python#46]
The output-to-html function is truncating my logs. How do I see the truncated data?

Thanks!!

**Comment by benpturner** [comment]
Hi, 

Sorry to hear that. Can you show me an obfuscated example of what you mean?

**Comment by chppppp** [comment]
Here is a screen shot https://imgur.com/a/U9OGmhT

This command is returning 24k lines. I am able to dump to a csv on the local system then pull that file. Wondering if there is a way to just have Posh log all that data. 

Thank you so much!!!!

**Comment by benpturner** [comment]
Hi, sorry it has too make lines so it doesnt dump to the CSV by default. You can use the fpc.py command that is also shipped to search for invoke-mimikatz
/root/> fpc.py -p /opt/ProjectX -c invoke-mimikatz

**Comment by chppppp** [comment]
Thanks Ben.
