### ISSUE TITLE
old implants handling after update

### ISSUE THREAD

**Issue by kumara19bara** [nettitude/PoshC2_Python#53]
Hi, 
is there a way to handle old implants.
I've got 4 implants but after I updated posh to the new version and keeping the old version's config file and certs, non of the older implants is working.
I get this message : _Error with SharpSocks or old implant connection - is SharpSocks running_
..... (the visited links)
and the screen is all red.
if there is a way to take back all the old implant i'll be gratefull, because connecting back to all the implant on the client machines and trying to restart the process is a pain in the ass.

Thank you.
Bara.

**Comment by benpturner** [comment]
All implants should be backward capable. If you are having problems, it might be worth rolling back via Git to the version you were on before.
